$OFS = "`r`n"
$scriptname = "itt.ps1"
# Variable to sync between runspaces
$sync = [Hashtable]::Synchronized(@{})
$sync.PSScriptRoot = $PSScriptRoot
$sync.configs = @{}

if (Test-Path -Path "$($scriptname)")
{
    Remove-Item -Force "$($scriptname)"
}

Write-output '
################################################################################################################
###                                                                                                          ###
###  This file is automatically generated DO NOT modify this file                                            ###
###                                                                                                          ###
################################################################################################################
' | Out-File ./$scriptname -Append -Encoding ascii

(Get-Content .\scripts\start.ps1).replace('#{ver}',"$(Get-Date -Format yy.MM.dd)") | Out-File ./$scriptname -Append -Encoding ascii 


Get-ChildItem .\functions -Recurse -File | ForEach-Object {
    Get-Content $psitem.FullName | Out-File ./$scriptname -Append -Encoding ascii 
}

Get-ChildItem .\config | Where-Object {$psitem.extension -eq ".json"} | ForEach-Object {
    $json = (Get-Content $psitem.FullName).replace("'","''")
    $sync.configs.$($psitem.BaseName) = $json | convertfrom-json
    Write-output "`$sync.configs.$($psitem.BaseName) = '$json' `| convertfrom-json" "  "| Out-File ./$scriptname -Append -Encoding ascii 
}




$xaml = (Get-Content .\xaml\window.xaml).replace("'","''")


# Assuming taps.xaml is in the same directory as main.ps1
$appXamlPath = Join-Path -Path $PSScriptRoot -ChildPath "xaml/controls/taps.xaml"

# Load the XAML content from inputApp.xaml
$appXamlContent = Get-Content -Path $appXamlPath -Raw

# Replace the placeholder in $inputXML with the content of inputApp.xaml
$xaml = $xaml -replace "{{Taps}}", $appXamlContent


Write-output "`$inputXML =  '$xaml'" | Out-File ./$scriptname -Append -Encoding ascii 

Get-Content .\scripts\loadXmal.ps1 | Out-File ./$scriptname -Append -Encoding ascii

Get-ChildItem .\loops -Recurse -File | ForEach-Object {
    
    Get-Content $psitem.FullName | Out-File ./$scriptname -Append -Encoding ascii 
}


Get-Content .\scripts\main.ps1 | Out-File ./$scriptname -Append -Encoding ascii

